In [1]:
import numpy as np

In [10]:
array1 = np.array([1,2,3,4,5])
array2 = np.array([[1,2,3,4,5],[1,3,5,4,5]])
array3 = np.array([[1,2,3,4,5],[1,3,5,3,2],[2,4,4,5,2]])
print(array1 ," , ")
print(array2, " , ")
print(array3, " , ")


[1 2 3 4 5]  , 
[[1 2 3 4 5]
 [1 3 5 4 5]]  , 
[[1 2 3 4 5]
 [1 3 5 3 2]
 [2 4 4 5 2]]  , 


In [11]:
# Criando um array com zeros
arr_zeros = np.zeros((3, 3))

# Criando um array com uns
arr_ones = np.ones((2, 4))

# Criando um array com valores aleatórios
arr_random = np.random.rand(3, 3)

print(arr_zeros)
print(arr_ones)
print(arr_random)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0.3416989  0.44016878 0.22809532]
 [0.87610457 0.76520766 0.50178242]
 [0.34746608 0.6747917  0.67719872]]


In [12]:
# Operações aritméticas
arr = np.array([1, 2, 3, 4, 5])
arr_sum = arr + 10
arr_product = arr * 2

# Funções estatísticas
mean = np.mean(arr)
std_dev = np.std(arr)

# Álgebra linear
matrix = np.array([[1, 2], [3, 4]])
det = np.linalg.det(matrix)

# Broadcasting
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2  # [5, 7, 9]